### ISSUE TITLE
Ist TrueQBF in NP oder in PSPACE?

### ISSUE THREAD

**Issue by MaxMatti** [cooox/theolog-ss2017#2]
In 2.8 bei Beispielen für PSPACE-Probleme wird gesagt, dass TrueQBF PSpace-hart ist. Es wird auch gesagt, dass sich TrueQBF auf SAT reduzieren lässt. Aber in 1.3 wird gesagt, dass SAT in NP liegt. Wenn ich das richtig verstanden habe, ist das ein Widerspruch. Ist in 2.8 statt SAT vielleicht QSAT (SAT mit Quantoren) gemeint?

**Comment by cooox** [comment]
> Es wird auch gesagt, dass sich TrueQBF auf SAT reduzieren lässt.

Ich glaube das ist ein Missverständnis: `SAT ≤ p TrueQBF` bedeutet, SAT lässt sich auf TrueQBF polynomiell reduzieren. Siehe hierzu VL11, Folie 18.

- SAT ist NP-vollständig
- _Satz: TrueQBF ist PSpace-hart._

Edit: Deine Frage „Ist TrueQBF in NP oder in PSPACE?“ habe ich damit übrigens nicht beantwortet, da aus der Folie nur hervorgeht, dass TrueQBF zumindest PSpace-hart ist.

**Comment by cooox** [comment]
Ein Blick in Vorlesung 12: _Satz: TrueQBF ist in PSpace._

**Comment by cooox** [comment]
TrueQBF: PSpace-hart auf PSpace-vollständig erweitert in 9766777e1bbe6b7a923a1bfad062447bfdfcfb98.
