### ISSUE TITLE
Lsg. Blatt 5 Aufgabe 1

### ISSUE THREAD

**Issue by TheAlexLichter** [cooox/theolog-ss2017#4]
Bei der a) der oben angegebenen Aufgabe müsste die Antwort doch eigentlich "falsch" sein, oder?

Wenn P ungleich NP, dann ist P eine echte Teilmenge von P. Damit wäre der Schnitt von P und NP P.

**Comment by cooox** [comment]
Edit: Hast Recht, es gilt P &#8898; NP = P &#8800; &empty;, egal ob P = NP oder P &ne; NP.
Fixed in 4b06c28ed0231ffcf7be534b54480b2fe6798448
