### ISSUE TITLE
Definition/Erklärung Satz von Rice

### ISSUE THREAD

**Issue by TheAlexLichter** [cooox/theolog-ss2017#5]
![image](https://user-images.githubusercontent.com/640208/28502571-8520b240-6ff5-11e7-931f-b352eb5a4f92.png)

Müsste es hier nicht anstatt _semi-entscheidbarer_ Sprachen, _turing-erkennbarer_ Sprachen heißen?

**Comment by cooox** [comment]
Semi-entscheidbar und Turing-erkennbar bezeichnen dasselbe, siehe FS VL 19 Folie 13. 
Steht auch in Kapitel 1.1 auf Seite 2.

**Comment by TheAlexLichter** [comment]
Alles klar, danke dir :)
